// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace practice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Shop", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Pname")
                        .HasColumnType("longtext");

                    b.Property<double>("Pprice")
                        .HasColumnType("double");

                    b.HasKey("Pid");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Pid = 101,
                            Pname = "Rajat Shop-1",
                            Pprice = 29999.990000000002
                        },
                        new
                        {
                            Pid = 102,
                            Pname = "Rajat Shop-2",
                            Pprice = 29999.990000000002
                        },
                        new
                        {
                            Pid = 103,
                            Pname = "Rajat Shop-3",
                            Pprice = 29999.990000000002
                        },
                        new
                        {
                            Pid = 104,
                            Pname = "Rajat Shop-4",
                            Pprice = 29999.990000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
